--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4 (Debian 16.4-1.pgdg120+1)
-- Dumped by pg_dump version 16.3

-- Started on 2024-09-06 04:04:20 +0530

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 238 (class 1259 OID 17472)
-- Name: Businesses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Businesses" (
                                     "Id" integer NOT NULL,
                                     "NameOfBusiness" character varying(100) NOT NULL,
                                     "AddressOfBusiness" character varying(255) NOT NULL,
                                     "RegistrationNumber" character varying(100) NOT NULL,
                                     "SharesOwned" character varying(50) NOT NULL,
                                     "ResidenceVisaInfoId" integer NOT NULL
);


ALTER TABLE public."Businesses" OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 17471)
-- Name: Businesses_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Businesses" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Businesses_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 17359)
-- Name: Childrens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Childrens" (
                                    "Id" integer NOT NULL,
                                    "Name" character varying(100) NOT NULL,
                                    "Gender" text NOT NULL,
                                    "PlaceOfBirth" text NOT NULL,
                                    "UserInfoId" integer NOT NULL
);


ALTER TABLE public."Childrens" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 17358)
-- Name: Childrens_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Childrens" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Childrens_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 17372)
-- Name: EmergencyContacts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EmergencyContacts" (
                                            "Id" integer NOT NULL,
                                            "Name" character varying(100) NOT NULL,
                                            "Address" character varying(255) NOT NULL,
                                            "Contact" character varying(20) NOT NULL,
                                            "Relationship" character varying(50),
                                            "UserInfoId" integer NOT NULL,
                                            "SpendableAmount" double precision DEFAULT 0.0 NOT NULL,
                                            "Support" text,
                                            "UsdAmount" double precision DEFAULT 0.0 NOT NULL,
                                            "nameOfCreditCard" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."EmergencyContacts" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 17371)
-- Name: EmergencyContacts_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EmergencyContacts" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EmergencyContacts_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 17448)
-- Name: EntryVisaApprovals; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EntryVisaApprovals" (
                                             "Id" integer NOT NULL,
                                             "VisaNumber" character varying(50) NOT NULL,
                                             "DateIssued" timestamp with time zone NOT NULL,
                                             "Purpose" character varying(50) NOT NULL,
                                             "EntryVisaInfoId" integer NOT NULL
);


ALTER TABLE public."EntryVisaApprovals" OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 17447)
-- Name: EntryVisaApprovals_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EntryVisaApprovals" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EntryVisaApprovals_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 17383)
-- Name: EntryVisaInfos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EntryVisaInfos" (
                                         "Id" integer NOT NULL,
                                         "ObjectOfVisit" character varying(50) NOT NULL,
                                         "ModeOfTravel" character varying(50) NOT NULL,
                                         "DateOfLeaving" timestamp with time zone NOT NULL,
                                         "LastPlaceOfResidence" character varying(100) NOT NULL,
                                         "DateOfIssue" timestamp with time zone NOT NULL,
                                         "ResidenceVisaNumber" character varying(50) NOT NULL,
                                         "HasRefusedVisa" text NOT NULL,
                                         "UserInfoId" integer NOT NULL,
                                         "LastObtainedVisa" text DEFAULT ''::text NOT NULL,
                                         "PeriodOfValidity" integer DEFAULT 0 NOT NULL,
                                         "PeriodOfVisitVisa" integer DEFAULT 0 NOT NULL
);


ALTER TABLE public."EntryVisaInfos" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 17382)
-- Name: EntryVisaInfos_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EntryVisaInfos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EntryVisaInfos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 17393)
-- Name: NaturalizationInfos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."NaturalizationInfos" (
                                              "UserInfoId" integer NOT NULL,
                                              "IsNaturalized" boolean NOT NULL,
                                              "NaturalizationDate" timestamp with time zone,
                                              "PlaceOfNaturalization" character varying(100) NOT NULL,
                                              "FormerNationality" character varying(50) NOT NULL,
                                              id integer NOT NULL
);


ALTER TABLE public."NaturalizationInfos" OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 17512)
-- Name: NaturalizationInfos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."NaturalizationInfos" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."NaturalizationInfos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 17403)
-- Name: Passports; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Passports" (
                                    "UserInfoId" integer NOT NULL,
                                    "Number" character varying(20) NOT NULL,
                                    "PlaceOfIssue" character varying(100) NOT NULL,
                                    "DateOfIssue" timestamp with time zone NOT NULL,
                                    "DateOfExpiry" timestamp with time zone NOT NULL,
                                    "Id" integer NOT NULL,
                                    "PreviousDateOfExpiry" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL,
                                    "PreviousDateOfIssue" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL,
                                    "PreviousNumber" text DEFAULT ''::text NOT NULL,
                                    "PreviousPlaceOfIssue" character varying(100) DEFAULT ''::character varying NOT NULL
);


ALTER TABLE public."Passports" OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 17508)
-- Name: Passports_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Passports" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Passports_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 17414)
-- Name: Professions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Professions" (
                                      "Id" integer NOT NULL,
                                      "NameOfWorkplace" character varying(100) NOT NULL,
                                      "AddressOfWorkplace" character varying(255) NOT NULL,
                                      "Email" character varying(100) NOT NULL,
                                      "Fax" character varying(20) NOT NULL,
                                      "UserInfoId" integer NOT NULL
);


ALTER TABLE public."Professions" OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 17413)
-- Name: Professions_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Professions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Professions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 17485)
-- Name: ResidenceVisaApprovals; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ResidenceVisaApprovals" (
                                                 "Id" integer NOT NULL,
                                                 "VisaNumber" character varying(50) NOT NULL,
                                                 "DateIssued" timestamp with time zone NOT NULL,
                                                 "Purpose" character varying(50) NOT NULL,
                                                 "ResidenceVisaInfoId" integer NOT NULL
);


ALTER TABLE public."ResidenceVisaApprovals" OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 17484)
-- Name: ResidenceVisaApprovals_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ResidenceVisaApprovals" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ResidenceVisaApprovals_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 17425)
-- Name: ResidenceVisaInfos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ResidenceVisaInfos" (
                                             "Id" integer NOT NULL,
                                             "DateOfArrival" timestamp with time zone NOT NULL,
                                             "ReasonForApplyingVisa" character varying(255) NOT NULL,
                                             "ApplyingFor" character varying(50) NOT NULL,
                                             "SalaryIncome" text NOT NULL,
                                             "UserInfoId" integer NOT NULL
);


ALTER TABLE public."ResidenceVisaInfos" OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 17424)
-- Name: ResidenceVisaInfos_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ResidenceVisaInfos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ResidenceVisaInfos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 17437)
-- Name: SpouseInfos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SpouseInfos" (
                                      "UserInfoId" integer NOT NULL,
                                      "Fullname" character varying(100) NOT NULL,
                                      "Nationality" character varying(50) NOT NULL,
                                      "PostalAddress" character varying(255) NOT NULL,
                                      "PassportNumber" character varying(20) NOT NULL,
                                      "DateOfExpiry" timestamp with time zone NOT NULL,
                                      "IsPrevious" boolean NOT NULL,
                                      "Id" integer NOT NULL
);


ALTER TABLE public."SpouseInfos" OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 17504)
-- Name: SpouseInfos_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."SpouseInfos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SpouseInfos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 17343)
-- Name: User; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."User" (
                               "UserID" integer NOT NULL,
                               "FirstName" text NOT NULL,
                               "LastName" text NOT NULL,
                               "AccountVerified" integer NOT NULL,
                               "MobileNumber" text NOT NULL,
                               "Email" text NOT NULL,
                               "Password" text NOT NULL,
                               "OldPassword" text[]
);


ALTER TABLE public."User" OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 17351)
-- Name: UserInfos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."UserInfos" (
                                    "Id" integer NOT NULL,
                                    "FullName" character varying(100) NOT NULL,
                                    "Nationality" character varying(50),
                                    "Gender" character varying(10),
                                    "DOB" timestamp with time zone NOT NULL,
                                    "BirthCountry" text,
                                    "BirthPlace" text,
                                    "Height" integer NOT NULL,
                                    "Peculiarity" character varying(255) NOT NULL,
                                    "DomicileAddress" character varying(255) NOT NULL,
                                    "AddressDuringSriLanka" character varying(255) NOT NULL,
                                    "Telephone" character varying(20) NOT NULL,
                                    "Mobile" character varying(20) NOT NULL,
                                    "Email" character varying(100) NOT NULL,
                                    "CivilStatus" integer NOT NULL,
                                    "UserID" integer NOT NULL,
                                    "Image" text DEFAULT ''::text NOT NULL,
                                    "Periodofvisit" integer DEFAULT 0 NOT NULL,
                                    "WorkSpaceAddress" text DEFAULT ''::text NOT NULL,
                                    "WorkSpaceEmail" text DEFAULT ''::text NOT NULL,
                                    "WorkSpaceName" character varying(100) DEFAULT ''::character varying NOT NULL
);


ALTER TABLE public."UserInfos" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 17350)
-- Name: UserInfos_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."UserInfos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserInfos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 17342)
-- Name: User_UserID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."User" ALTER COLUMN "UserID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."User_UserID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 17459)
-- Name: VisaExtensionInfos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."VisaExtensionInfos" (
                                             "Id" integer NOT NULL,
                                             "PeriodVisaRequiredFor" character varying(100) NOT NULL,
                                             "ExtentVisaRequiredFor" character varying(50) NOT NULL,
                                             "CurrencyType" text NOT NULL,
                                             "Amount" numeric NOT NULL,
                                             "AmountCashed" numeric NOT NULL,
                                             "ExchangeBroughtIn" numeric NOT NULL,
                                             "CreditCardAvailable" boolean NOT NULL,
                                             "EntryVisaInfoId" integer NOT NULL
);


ALTER TABLE public."VisaExtensionInfos" OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 17458)
-- Name: VisaExtensionInfos_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."VisaExtensionInfos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."VisaExtensionInfos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 17337)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
                                                "MigrationId" character varying(150) NOT NULL,
                                                "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 3507 (class 0 OID 17472)
-- Dependencies: 238
-- Data for Name: Businesses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Businesses" ("Id", "NameOfBusiness", "AddressOfBusiness", "RegistrationNumber", "SharesOwned", "ResidenceVisaInfoId") FROM stdin;
\.


--
-- TOC entry 3490 (class 0 OID 17359)
-- Dependencies: 221
-- Data for Name: Childrens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Childrens" ("Id", "Name", "Gender", "PlaceOfBirth", "UserInfoId") FROM stdin;
\.


--
-- TOC entry 3492 (class 0 OID 17372)
-- Dependencies: 223
-- Data for Name: EmergencyContacts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."EmergencyContacts" ("Id", "Name", "Address", "Contact", "Relationship", "UserInfoId", "SpendableAmount", "Support", "UsdAmount", "nameOfCreditCard") FROM stdin;
\.


--
-- TOC entry 3503 (class 0 OID 17448)
-- Dependencies: 234
-- Data for Name: EntryVisaApprovals; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."EntryVisaApprovals" ("Id", "VisaNumber", "DateIssued", "Purpose", "EntryVisaInfoId") FROM stdin;
\.


--
-- TOC entry 3494 (class 0 OID 17383)
-- Dependencies: 225
-- Data for Name: EntryVisaInfos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."EntryVisaInfos" ("Id", "ObjectOfVisit", "ModeOfTravel", "DateOfLeaving", "LastPlaceOfResidence", "DateOfIssue", "ResidenceVisaNumber", "HasRefusedVisa", "UserInfoId", "LastObtainedVisa", "PeriodOfValidity", "PeriodOfVisitVisa") FROM stdin;
\.


--
-- TOC entry 3495 (class 0 OID 17393)
-- Dependencies: 226
-- Data for Name: NaturalizationInfos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."NaturalizationInfos" ("UserInfoId", "IsNaturalized", "NaturalizationDate", "PlaceOfNaturalization", "FormerNationality", id) FROM stdin;
\.


--
-- TOC entry 3496 (class 0 OID 17403)
-- Dependencies: 227
-- Data for Name: Passports; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Passports" ("UserInfoId", "Number", "PlaceOfIssue", "DateOfIssue", "DateOfExpiry", "Id", "PreviousDateOfExpiry", "PreviousDateOfIssue", "PreviousNumber", "PreviousPlaceOfIssue") FROM stdin;
\.


--
-- TOC entry 3498 (class 0 OID 17414)
-- Dependencies: 229
-- Data for Name: Professions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Professions" ("Id", "NameOfWorkplace", "AddressOfWorkplace", "Email", "Fax", "UserInfoId") FROM stdin;
\.


--
-- TOC entry 3509 (class 0 OID 17485)
-- Dependencies: 240
-- Data for Name: ResidenceVisaApprovals; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ResidenceVisaApprovals" ("Id", "VisaNumber", "DateIssued", "Purpose", "ResidenceVisaInfoId") FROM stdin;
\.


--
-- TOC entry 3500 (class 0 OID 17425)
-- Dependencies: 231
-- Data for Name: ResidenceVisaInfos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ResidenceVisaInfos" ("Id", "DateOfArrival", "ReasonForApplyingVisa", "ApplyingFor", "SalaryIncome", "UserInfoId") FROM stdin;
\.


--
-- TOC entry 3501 (class 0 OID 17437)
-- Dependencies: 232
-- Data for Name: SpouseInfos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."SpouseInfos" ("UserInfoId", "Fullname", "Nationality", "PostalAddress", "PassportNumber", "DateOfExpiry", "IsPrevious", "Id") FROM stdin;
\.


--
-- TOC entry 3486 (class 0 OID 17343)
-- Dependencies: 217
-- Data for Name: User; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."User" ("UserID", "FirstName", "LastName", "AccountVerified", "MobileNumber", "Email", "Password", "OldPassword") FROM stdin;
\.


--
-- TOC entry 3488 (class 0 OID 17351)
-- Dependencies: 219
-- Data for Name: UserInfos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."UserInfos" ("Id", "FullName", "Nationality", "Gender", "DOB", "BirthCountry", "BirthPlace", "Height", "Peculiarity", "DomicileAddress", "AddressDuringSriLanka", "Telephone", "Mobile", "Email", "CivilStatus", "UserID", "Image", "Periodofvisit", "WorkSpaceAddress", "WorkSpaceEmail", "WorkSpaceName") FROM stdin;
\.


--
-- TOC entry 3505 (class 0 OID 17459)
-- Dependencies: 236
-- Data for Name: VisaExtensionInfos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."VisaExtensionInfos" ("Id", "PeriodVisaRequiredFor", "ExtentVisaRequiredFor", "CurrencyType", "Amount", "AmountCashed", "ExchangeBroughtIn", "CreditCardAvailable", "EntryVisaInfoId") FROM stdin;
\.


--
-- TOC entry 3484 (class 0 OID 17337)
-- Dependencies: 215
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20240904212431_allmodels	8.0.8
20240905091159_modelsnew	8.0.8
20240905100046_modelsnew2	8.0.8
20240905223200_dbform2	8.0.8
\.


--
-- TOC entry 3518 (class 0 OID 0)
-- Dependencies: 237
-- Name: Businesses_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Businesses_Id_seq"', 1, false);


--
-- TOC entry 3519 (class 0 OID 0)
-- Dependencies: 220
-- Name: Childrens_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Childrens_Id_seq"', 1, false);


--
-- TOC entry 3520 (class 0 OID 0)
-- Dependencies: 222
-- Name: EmergencyContacts_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EmergencyContacts_Id_seq"', 1, false);


--
-- TOC entry 3521 (class 0 OID 0)
-- Dependencies: 233
-- Name: EntryVisaApprovals_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EntryVisaApprovals_Id_seq"', 1, false);


--
-- TOC entry 3522 (class 0 OID 0)
-- Dependencies: 224
-- Name: EntryVisaInfos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EntryVisaInfos_Id_seq"', 1, false);


--
-- TOC entry 3523 (class 0 OID 0)
-- Dependencies: 243
-- Name: NaturalizationInfos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."NaturalizationInfos_id_seq"', 1, false);


--
-- TOC entry 3524 (class 0 OID 0)
-- Dependencies: 242
-- Name: Passports_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Passports_Id_seq"', 1, false);


--
-- TOC entry 3525 (class 0 OID 0)
-- Dependencies: 228
-- Name: Professions_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Professions_Id_seq"', 1, false);


--
-- TOC entry 3526 (class 0 OID 0)
-- Dependencies: 239
-- Name: ResidenceVisaApprovals_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ResidenceVisaApprovals_Id_seq"', 1, false);


--
-- TOC entry 3527 (class 0 OID 0)
-- Dependencies: 230
-- Name: ResidenceVisaInfos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ResidenceVisaInfos_Id_seq"', 1, false);


--
-- TOC entry 3528 (class 0 OID 0)
-- Dependencies: 241
-- Name: SpouseInfos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."SpouseInfos_Id_seq"', 1, false);


--
-- TOC entry 3529 (class 0 OID 0)
-- Dependencies: 218
-- Name: UserInfos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."UserInfos_Id_seq"', 1, false);


--
-- TOC entry 3530 (class 0 OID 0)
-- Dependencies: 216
-- Name: User_UserID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."User_UserID_seq"', 1, false);


--
-- TOC entry 3531 (class 0 OID 0)
-- Dependencies: 235
-- Name: VisaExtensionInfos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."VisaExtensionInfos_Id_seq"', 1, false);


--
-- TOC entry 3325 (class 2606 OID 17478)
-- Name: Businesses PK_Businesses; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Businesses"
    ADD CONSTRAINT "PK_Businesses" PRIMARY KEY ("Id");


--
-- TOC entry 3295 (class 2606 OID 17365)
-- Name: Childrens PK_Childrens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Childrens"
    ADD CONSTRAINT "PK_Childrens" PRIMARY KEY ("Id");


--
-- TOC entry 3298 (class 2606 OID 17376)
-- Name: EmergencyContacts PK_EmergencyContacts; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EmergencyContacts"
    ADD CONSTRAINT "PK_EmergencyContacts" PRIMARY KEY ("Id");


--
-- TOC entry 3319 (class 2606 OID 17452)
-- Name: EntryVisaApprovals PK_EntryVisaApprovals; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EntryVisaApprovals"
    ADD CONSTRAINT "PK_EntryVisaApprovals" PRIMARY KEY ("Id");


--
-- TOC entry 3301 (class 2606 OID 17387)
-- Name: EntryVisaInfos PK_EntryVisaInfos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EntryVisaInfos"
    ADD CONSTRAINT "PK_EntryVisaInfos" PRIMARY KEY ("Id");


--
-- TOC entry 3304 (class 2606 OID 17521)
-- Name: NaturalizationInfos PK_NaturalizationInfos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."NaturalizationInfos"
    ADD CONSTRAINT "PK_NaturalizationInfos" PRIMARY KEY (id);


--
-- TOC entry 3307 (class 2606 OID 17519)
-- Name: Passports PK_Passports; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Passports"
    ADD CONSTRAINT "PK_Passports" PRIMARY KEY ("Id");


--
-- TOC entry 3310 (class 2606 OID 17418)
-- Name: Professions PK_Professions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Professions"
    ADD CONSTRAINT "PK_Professions" PRIMARY KEY ("Id");


--
-- TOC entry 3328 (class 2606 OID 17489)
-- Name: ResidenceVisaApprovals PK_ResidenceVisaApprovals; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ResidenceVisaApprovals"
    ADD CONSTRAINT "PK_ResidenceVisaApprovals" PRIMARY KEY ("Id");


--
-- TOC entry 3313 (class 2606 OID 17431)
-- Name: ResidenceVisaInfos PK_ResidenceVisaInfos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ResidenceVisaInfos"
    ADD CONSTRAINT "PK_ResidenceVisaInfos" PRIMARY KEY ("Id");


--
-- TOC entry 3316 (class 2606 OID 17517)
-- Name: SpouseInfos PK_SpouseInfos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SpouseInfos"
    ADD CONSTRAINT "PK_SpouseInfos" PRIMARY KEY ("Id");


--
-- TOC entry 3290 (class 2606 OID 17349)
-- Name: User PK_User; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "PK_User" PRIMARY KEY ("UserID");


--
-- TOC entry 3292 (class 2606 OID 17357)
-- Name: UserInfos PK_UserInfos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserInfos"
    ADD CONSTRAINT "PK_UserInfos" PRIMARY KEY ("Id");


--
-- TOC entry 3322 (class 2606 OID 17465)
-- Name: VisaExtensionInfos PK_VisaExtensionInfos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."VisaExtensionInfos"
    ADD CONSTRAINT "PK_VisaExtensionInfos" PRIMARY KEY ("Id");


--
-- TOC entry 3288 (class 2606 OID 17341)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3323 (class 1259 OID 17495)
-- Name: IX_Businesses_ResidenceVisaInfoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Businesses_ResidenceVisaInfoId" ON public."Businesses" USING btree ("ResidenceVisaInfoId");


--
-- TOC entry 3293 (class 1259 OID 17496)
-- Name: IX_Childrens_UserInfoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Childrens_UserInfoId" ON public."Childrens" USING btree ("UserInfoId");


--
-- TOC entry 3296 (class 1259 OID 17497)
-- Name: IX_EmergencyContacts_UserInfoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_EmergencyContacts_UserInfoId" ON public."EmergencyContacts" USING btree ("UserInfoId");


--
-- TOC entry 3317 (class 1259 OID 17498)
-- Name: IX_EntryVisaApprovals_EntryVisaInfoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_EntryVisaApprovals_EntryVisaInfoId" ON public."EntryVisaApprovals" USING btree ("EntryVisaInfoId");


--
-- TOC entry 3299 (class 1259 OID 17499)
-- Name: IX_EntryVisaInfos_UserInfoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_EntryVisaInfos_UserInfoId" ON public."EntryVisaInfos" USING btree ("UserInfoId");


--
-- TOC entry 3302 (class 1259 OID 17524)
-- Name: IX_NaturalizationInfos_UserInfoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_NaturalizationInfos_UserInfoId" ON public."NaturalizationInfos" USING btree ("UserInfoId");


--
-- TOC entry 3305 (class 1259 OID 17523)
-- Name: IX_Passports_UserInfoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Passports_UserInfoId" ON public."Passports" USING btree ("UserInfoId");


--
-- TOC entry 3308 (class 1259 OID 17500)
-- Name: IX_Professions_UserInfoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Professions_UserInfoId" ON public."Professions" USING btree ("UserInfoId");


--
-- TOC entry 3326 (class 1259 OID 17501)
-- Name: IX_ResidenceVisaApprovals_ResidenceVisaInfoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ResidenceVisaApprovals_ResidenceVisaInfoId" ON public."ResidenceVisaApprovals" USING btree ("ResidenceVisaInfoId");


--
-- TOC entry 3311 (class 1259 OID 17502)
-- Name: IX_ResidenceVisaInfos_UserInfoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_ResidenceVisaInfos_UserInfoId" ON public."ResidenceVisaInfos" USING btree ("UserInfoId");


--
-- TOC entry 3314 (class 1259 OID 17522)
-- Name: IX_SpouseInfos_UserInfoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_SpouseInfos_UserInfoId" ON public."SpouseInfos" USING btree ("UserInfoId");


--
-- TOC entry 3320 (class 1259 OID 17503)
-- Name: IX_VisaExtensionInfos_EntryVisaInfoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_VisaExtensionInfos_EntryVisaInfoId" ON public."VisaExtensionInfos" USING btree ("EntryVisaInfoId");


--
-- TOC entry 3339 (class 2606 OID 17479)
-- Name: Businesses FK_Businesses_ResidenceVisaInfos_ResidenceVisaInfoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Businesses"
    ADD CONSTRAINT "FK_Businesses_ResidenceVisaInfos_ResidenceVisaInfoId" FOREIGN KEY ("ResidenceVisaInfoId") REFERENCES public."ResidenceVisaInfos"("Id") ON DELETE CASCADE;


--
-- TOC entry 3329 (class 2606 OID 17366)
-- Name: Childrens FK_Childrens_UserInfos_UserInfoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Childrens"
    ADD CONSTRAINT "FK_Childrens_UserInfos_UserInfoId" FOREIGN KEY ("UserInfoId") REFERENCES public."UserInfos"("Id") ON DELETE CASCADE;


--
-- TOC entry 3330 (class 2606 OID 17377)
-- Name: EmergencyContacts FK_EmergencyContacts_UserInfos_UserInfoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EmergencyContacts"
    ADD CONSTRAINT "FK_EmergencyContacts_UserInfos_UserInfoId" FOREIGN KEY ("UserInfoId") REFERENCES public."UserInfos"("Id") ON DELETE CASCADE;


--
-- TOC entry 3337 (class 2606 OID 17453)
-- Name: EntryVisaApprovals FK_EntryVisaApprovals_EntryVisaInfos_EntryVisaInfoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EntryVisaApprovals"
    ADD CONSTRAINT "FK_EntryVisaApprovals_EntryVisaInfos_EntryVisaInfoId" FOREIGN KEY ("EntryVisaInfoId") REFERENCES public."EntryVisaInfos"("Id") ON DELETE CASCADE;


--
-- TOC entry 3331 (class 2606 OID 17388)
-- Name: EntryVisaInfos FK_EntryVisaInfos_UserInfos_UserInfoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EntryVisaInfos"
    ADD CONSTRAINT "FK_EntryVisaInfos_UserInfos_UserInfoId" FOREIGN KEY ("UserInfoId") REFERENCES public."UserInfos"("Id") ON DELETE CASCADE;


--
-- TOC entry 3332 (class 2606 OID 17398)
-- Name: NaturalizationInfos FK_NaturalizationInfos_UserInfos_UserInfoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."NaturalizationInfos"
    ADD CONSTRAINT "FK_NaturalizationInfos_UserInfos_UserInfoId" FOREIGN KEY ("UserInfoId") REFERENCES public."UserInfos"("Id") ON DELETE CASCADE;


--
-- TOC entry 3333 (class 2606 OID 17408)
-- Name: Passports FK_Passports_UserInfos_UserInfoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Passports"
    ADD CONSTRAINT "FK_Passports_UserInfos_UserInfoId" FOREIGN KEY ("UserInfoId") REFERENCES public."UserInfos"("Id") ON DELETE CASCADE;


--
-- TOC entry 3334 (class 2606 OID 17419)
-- Name: Professions FK_Professions_UserInfos_UserInfoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Professions"
    ADD CONSTRAINT "FK_Professions_UserInfos_UserInfoId" FOREIGN KEY ("UserInfoId") REFERENCES public."UserInfos"("Id") ON DELETE CASCADE;


--
-- TOC entry 3340 (class 2606 OID 17490)
-- Name: ResidenceVisaApprovals FK_ResidenceVisaApprovals_ResidenceVisaInfos_ResidenceVisaInfo~; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ResidenceVisaApprovals"
    ADD CONSTRAINT "FK_ResidenceVisaApprovals_ResidenceVisaInfos_ResidenceVisaInfo~" FOREIGN KEY ("ResidenceVisaInfoId") REFERENCES public."ResidenceVisaInfos"("Id") ON DELETE CASCADE;


--
-- TOC entry 3335 (class 2606 OID 17432)
-- Name: ResidenceVisaInfos FK_ResidenceVisaInfos_UserInfos_UserInfoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ResidenceVisaInfos"
    ADD CONSTRAINT "FK_ResidenceVisaInfos_UserInfos_UserInfoId" FOREIGN KEY ("UserInfoId") REFERENCES public."UserInfos"("Id") ON DELETE CASCADE;


--
-- TOC entry 3336 (class 2606 OID 17442)
-- Name: SpouseInfos FK_SpouseInfos_UserInfos_UserInfoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SpouseInfos"
    ADD CONSTRAINT "FK_SpouseInfos_UserInfos_UserInfoId" FOREIGN KEY ("UserInfoId") REFERENCES public."UserInfos"("Id") ON DELETE CASCADE;


--
-- TOC entry 3338 (class 2606 OID 17466)
-- Name: VisaExtensionInfos FK_VisaExtensionInfos_EntryVisaInfos_EntryVisaInfoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."VisaExtensionInfos"
    ADD CONSTRAINT "FK_VisaExtensionInfos_EntryVisaInfos_EntryVisaInfoId" FOREIGN KEY ("EntryVisaInfoId") REFERENCES public."EntryVisaInfos"("Id") ON DELETE CASCADE;


-- Completed on 2024-09-06 04:04:20 +0530

--
-- PostgreSQL database dump complete
--

